export const leaders = [
  {
    image: "/assets/profile_photos/hzli.jpg",
    title: "Hanze Li",
    subtitle:
      "GeekPie 主席 | GeekPie_HardCore 负责人 | RA @ METAL | PRiSM 漫研社音游部部长 & 技术支持",
    handle: "@Maotechh",
    url: "https://github.com/Maotechh",
  },
  {
    image: "/assets/profile_photos/zbhe.jpg",
    title: "Zebang He",
    subtitle:
      "GeekPie_HPC & GeekPie_CTF 负责人 | Intern @ 上海交通大学 IPADS 实验室, 九坤投资",
    handle: "@HeZeBang",
    url: "https://github.com/HeZeBang",
  },
  {
    image: "/assets/profile_photos/szzhao.jpg",
    title: "Sizhe Zhao",
    subtitle:
      "GeekPie 副主席 | 镜像站 SRE | GeekPie_DevOps 负责人 | Intern @ 九坤投资 | NixOS CN Core Member",
    handle: "@Prince213",
    url: "https://github.com/Prince213",
  },
  {
    image: "/assets/profile_photos/hyai.jpg",
    title: "Hengyu Ai",
    subtitle: "GeekPie 副主席 | Intern @ NC State University",
    handle: "@AstatineAi",
    url: "https://github.com/AstatineAi",
  },
  {
    image: "/assets/profile_photos/lthan.jpg",
    title: "Letong Han",
    subtitle:
      "GeekPie_Arch 负责人 | 龙芯杯全国特等奖 | 北京开源芯片研究院 | “一生一芯”计划助教",
    handle: "@DFPMTS",
    url: "https://github.com/DFPMTS",
  },
  {
    image: "/assets/profile_photos/kph.jpg",
    title: "Penghao Kuang",
    subtitle: "ACM 社团主席 | RA @ Kewei Tu",
    handle: "@kuangpenghao",
    url: "https://github.com/kuangpenghao",
  },
  {
    image: "/assets/profile_photos/klin.jpg",
    title: "Kaizhan Lin",
    subtitle:
      "GeekPie_HardCore 联席负责人 | SenseUs 2025 1st Winner | Intern @ 九坤投资",
    handle: "@clateral912",
    url: "https://github.com/clateral912",
  },
  {
    image: "/assets/profile_photos/chtzhong.jpg",
    title: "Chentao Zhong",
    subtitle: "GeekPie_404 前后端团队负责人 | CoursePrettier | Intern @ Deemos",
    handle: "@GregTaoo",
    url: "https://github.com/GregTaoo",
  },
  {
    image: "/assets/profile_photos/lliu.jpg",
    title: "LINJIA LIU",
    subtitle: "Open Course",
    handle: "@CNDY1390",
    url: "https://github.com/CNDY1390",
  },
];
export const alumni = [
  {
    image: "/assets/profile_photos/wlyu.jpg",
    title: "Wentao Lyu",
    subtitle: "Founder of GeekPie_ | CTO and Co-Founder @ Stereye",
    handle: "2018",
    url: "https://www.linkedin.com/in/wenyaolyu",
  },
  {
    image: "/assets/profile_photos/jhshi.jpg",
    title: "Jiahe Shi",
    subtitle: "2nd President of GeekPie_ | 博士研究生 @ 上海科技大学",
    handle: "2018 ", // 加上空格破坏姓名字母顺序
    url: "https://www.linkedin.com/in/sjhstone",
  },
  {
    image: "/assets/profile_photos/qdeng.jpg",
    title: "Qi Deng",
    subtitle: "博士研究生 @ 上海科技大学 | ShanghaiTechRicLab",
    handle: "2018 ",
    url: "https://github.com/nerdneilsfield",
  },
  {
    image: "/assets/profile_photos/yzyuan.jpg",
    title: "Yunzhe Yuan",
    subtitle: "PhD Student @ University of St Andrews | Ex RA @ 北京大学",
    handle: "2018 ",
    url: "https://www.linkedin.com/in/yunzhe-yuan-001574102/?locale=en_US",
  },
  {
    image: "/assets/profile_photos/xiongzhip.jpg",
    title: "Erik Xiong",
    subtitle: "博士研究生 @ 上海科技大学 | 上海科技大学药物发现与设计中心",
    handle: "2019",
    url: "https://github.com/xiongzhp",
  },
  {
    image: "/assets/profile_photos/zyang.jpg",
    title: "Yang Zhou",
    subtitle:
      "Robotics PhD Candidate @ NYU | RoboMaster 社团创立者 | Ex Intern @ Carnegie Mellon University",
    handle: "2019",
    url: "https://www.linkedin.com/in/yangrobotics/",
  },
  {
    image: "/assets/profile_photos/zxie.jpg",
    title: "Zhiqiang Xie",
    subtitle: "PhD Student @ Stanford",
    handle: "2019",
    url: "https://www.linkedin.com/in/xiezhq/",
  },
  {
    image: "/assets/profile_photos/xizhao.png",
    title: "Xiting Zhao",
    subtitle: "博士研究生 @ 上海科技大学",
    handle: "2019",
    url: "https://robotics.shanghaitech.edu.cn/people/zhxt",
  },
  {
    image: "/assets/profile_photos/yyrong.jpg",
    title: "Yuyang Rong",
    subtitle: "Research Scientise @ Meta | Ex @ UC Davis, AMD, ByteDance",
    handle: "2019",
    url: "https://www.linkedin.com/in/yuyang-peter-rong-648109127",
  },
  {
    image: "/assets/profile_photos/jysu.jpg",
    title: "Junyan Su",
    subtitle: "PhD Student @ City University of Hong Kong",
    handle: "2019",
    url: "https://www.linkedin.com/in/junyan-su-12649828b",
  },
  {
    image: "/assets/profile_photos/zhzhao.jpg",
    title: "Zehao Zhao",
    subtitle:
      "IAMCAS/PAISATELLITE - 主任设计师/项目负责人 @ 中国科学院微小卫星创新研究院 | 前 GeekPie_ Robotics & Hardware 负责人",
    handle: "2020",
    url: "https://www.linkedin.com/in/%E6%B3%BD%E6%B5%A9-%E8%B5%B5-08463a167/",
  },
  {
    image: "/assets/profile_photos/yjing.png",
    title: "Yuzhuo Jing",
    subtitle: "Ph.D. student @ University of Michigan",
    handle: "2020",
    url: "https://www.linkedin.com/in/robert-king-s/",
  },
  {
    image: "/assets/profile_photos/qqin.jpg",
    title: "Qi Qin",
    subtitle: "Senior Security Researcher @ Sec3",
    handle: "2020",
    url: "https://www.linkedin.com/in/leoq7/",
  },
  {
    image: "/assets/profile_photos/xsong.jpeg",
    title: "Xiaoyu Song",
    subtitle:
      "PhD Student @ UT Dallas | Former @ Roblox/Microsoft/Google/Microsoft",
    handle: "2020",
    url: "https://www.linkedin.com/in/xiaoyu-lucy-song/",
  },
  {
    image: "/assets/profile_photos/pxia.jpg",
    title: "Philip (Yincen) Xia",
    subtitle: "Hyper3d.ai | Ex Tesla | UPenn | Ex Microsoft & Meta",
    handle: "2020",
    url: "https://www.linkedin.com/in/philipxyc/?locale=en_US",
  },
  {
    image: "/assets/profile_photos/dingtj.webp",
    title: "Tianjiao Ding",
    subtitle:
      "PhD Student @ University of Pennsylvania | Innovation in Data Engineering and Science (IDEAS)",
    handle: "2020",
    url: "https://github.com/tianjiaoding",
  },
  {
    image: "/assets/profile_photos/zhdiao.jpg",
    title: "Zihao (Eric) Diao",
    subtitle:
      "Co-Founder & Backend Engineering Director | Software Engineer @ Deemos | GeekPie SysAdmin",
    handle: "2021",
    url: "https://www.linkedin.com/in/zihao-diao-10268490/",
  },
  {
    image: "/assets/profile_photos/jwluo.jpg",
    title: "Jianwen Luo",
    subtitle: "Placeholder | 前 GeekPie_ FPGA 负责人",
    handle: "2021",
    url: "https://github.com/luojw-dwr",
  },
  {
    image: "/assets/profile_photos/hjing.jpg",
    title: "Haotian Jing",
    subtitle: "系统工程师 @ 思勰投资",
    handle: "2022",
    url: "#", // prefers not to disclose
  },
  {
    image: "/assets/profile_photos/lzhang.jpg",
    title: "Longwen Zhang",
    subtitle: "Co-Founder @ Deemos | 博士研究生 @ 上海科技大学",
    handle: "2022",
    url: "https://www.linkedin.com/in/longwen-zhang-73354a183/",
  },
  {
    image: "/assets/profile_photos/qzhang.jpg",
    title: "Qixuan Zhang",
    subtitle:
      "CTO @ Deemos｜HYPER3D.AI - Rodin｜Computer Graphics & GenAI Research｜🏆One Best Paper Award and two Honorable mentions at SIGGRAPH",
    handle: "2022",
    url: "https://www.linkedin.com/in/qx-zhang/",
  },
  {
    image: "/assets/profile_photos/yyang.jpg",
    title: "Yiwei Yang",
    subtitle:
      "Co-Founder of zett.ai | PhD Student @ University of California, Santa Cruz",
    handle: "2022",
    url: "https://www.linkedin.com/in/yiwei-yang-56b920166/",
  },
  {
    image: "/assets/profile_photos/fqin.jpg",
    title: "Feiran Qin",
    subtitle:
      "PhD Student @ NC State University | Ex Intern @ UIUC | 安同开源社区",
    handle: "2023",
    url: "https://www.linkedin.com/in/feiranqin/",
  },
  {
    image: "/assets/profile_photos/szhang.jpg",
    title: "Siyuan Zhang",
    subtitle: "PhD Student @ Ohio State University",
    handle: "2023",
    url: "https://www.linkedin.com/in/murezsy/",
  },
  {
    image: "/assets/profile_photos/hlin.jpeg",
    title: "Hongyang Lin",
    subtitle: "Technical Manager @ Deemos | 博士研究生 @ 上海科技大学",
    handle: "2024",
    url: "https://www.linkedin.com/in/hongyang-lin-4a0109207/",
  },
  {
    image: "/assets/profile_photos/zli.jpeg",
    title: "Zongze Li",
    subtitle: "PhD student @ University of Chicago",
    handle: "2024",
    url: "https://www.linkedin.com/in/zongze-li-45710a2a8/",
  },
  {
    image: "/assets/profile_photos/jcheng.jpg",
    title: "Jiajun Cheng",
    subtitle: "PhD Student @ University of California, Riverside",
    handle: "2024",
    url: "https://www.linkedin.com/in/jiajun-cheng-47926a344/",
  },
  {
    image: "/assets/profile_photos/ahu.jpg",
    title: "Aibo Hu",
    subtitle: "Software Engineer @ Jump Trading",
    handle: "2025",
    url: "https://www.linkedin.com/in/aibo-hu-590b0325a/",
  },
  {
    image: "/assets/profile_photos/zye.jpeg",
    title: "Zhe Ye",
    subtitle: "PhD Student @ University of California, Berkeley",
    handle: "2022",
    url: "https://www.linkedin.com/in/zheye/",
  },
  {
    image: "/assets/profile_photos/jdu.png",
    title: "Jiaying Du",
    subtitle: "Creator @ Bilibili",
    handle: "2026",
    url: "https://space.bilibili.com/11000198",
  },
  {
    image: "/assets/profile_photos/lhuang.jpg",
    title: "Lei Huang",
    subtitle: "MS Student @ UIUC | Quant Sys @ 思勰投资",
    handle: "2025",
    url: "https://www.linkedin.com/in/lei-huang-117102355/",
  },
  {
    image: "/assets/profile_photos/lyang.jpg",
    title: "Linshu Yang",
    subtitle: "MCS@UIUC | ex-Infra@UbiQuant | ex-RI@MPI | ex-SDE@Tencent",
    handle: "2025",
    url: "https://www.linkedin.com/in/ly4ng/",
  },
  {
    image: "/assets/profile_photos/teafrogsf.jpg",
    title: "Yuhan Cao",
    subtitle:
      "RA @ University of California, Berkeley | Former @ 清华叉院, 微软亚洲研究院, 北京大学 | SI 100+ 创立者 | CourseBench 项目经理",
    handle: "2025",
    url: "https://teafrogsf.github.io/",
  },
  {
    image: "/assets/profile_photos/ymzhang.png",
    title: "Yiming Chen",
    subtitle: "硕士研究生 @ 中国科学院大学",
    handle: "2025",
    url: "https://www.linkedin.com/in/yiming-chen-6528a3384/",
  },
  {
    image: "/assets/profile_photos/qzhao.jpg",
    title: "Qingcheng Zhao",
    subtitle:
      "PhD Student @ University of Toronto | SI 100+ / CourseBench 创立者 | 曾主办多场优质 Workshops 与校内活动",
    handle: "2025",
    url: "https://www.linkedin.com/in/qingcheng-zhao-a76631238/",
  },
  {
    image: "/assets/profile_photos/xwen.jpg",
    title: "Xuanjun Wen",
    subtitle: "Open Source Contributor @ GitHub",
    handle: "2025",
    url: "https://github.com/wenxuanjun",
  },
  {
    image: "/assets/profile_photos/yzhang.png",
    title: "Yichi Zhang",
    subtitle: "Software Engineer @ 九坤投资",
    handle: "2025",
    url: "https://www.linkedin.com/in/yichi-zhang-3a61022a0/",
  },
  {
    image: "/assets/profile_photos/zwang.jpg",
    title: "Ziqi Wang",
    subtitle: "MS Student @ Ohio State University 2025",
    handle: "2025",
    url: "https://www.linkedin.com/in/tacoin/",
  },
  {
    image: "/assets/profile_photos/hzhang.jpg",
    title: "Hanrui Zhang",
    subtitle: "Quantitative Engineer @ 九坤投资",
    handle: "2026",
    url: "https://www.linkedin.com/in/hanrui-zhang-0b323b381/",
  },
  {
    image: "/assets/profile_photos/mhong.jpeg",
    title: "Mutian Hong",
    subtitle: "Founder of DataTech | 博士研究生 @ 西湖大学",
    handle: "2026",
    url: "https://ori233.icu/",
  },
  {
    image: "/assets/profile_photos/xli.jpg",
    title: "Xiang Li",
    subtitle: "系统开发工程师 @ 思勰投资",
    handle: "2026",
    url: "https://www.linkedin.com/in/xiang-li-634568367/",
  },
  {
    image: "/assets/profile_photos/xjiang.jpg",
    title: "Xinyue Jiang",
    subtitle: "Performance Engineer @ NVIDIA",
    handle: "2026",
    url: "https://www.linkedin.com/in/xinyue-jiang-cn-4b3931366/",
  },
  {
    image: "/assets/profile_photos/plong.jpg",
    title: "Pengyu Long",
    subtitle: "博士研究生 @ 上海科技大学",
    handle: "2025",
    url: "https://github.com/YaeSakuraL",
  },
  {
    image: "/assets/profile_photos/sxu.jpeg",
    title: "Sijie Xu",
    subtitle: "博士研究生 @ 上海科技大学",
    handle: "2025",
    url: "https://github.com/xsjk",
  },
  {
    image: "/assets/profile_photos/lthan.jpg",
    title: "Letong Han",
    subtitle: "硕士研究生 @ 上科大 & 北京开源芯片研究院",
    handle: "2025",
    url: "https://github.com/DFPMTS",
  },
]
  .sort((a, b) => a.title.localeCompare(b.title))
  .sort((a, b) => a.handle.localeCompare(b.handle));
